backend:
  name: github
  repo: SoftDevRunner/sembo-site

publish_mode: editorial_workflow
media_folder: "src/images/postImages" # Media files will be stored in the repo under images/uploads
public_folder: "../../src/images/postImages"


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog",required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: true}