---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Upload Post
  create: all
  match: "**/*"
- type: heading
  label: SideBar
- type: directory
  path: ''
  label: manage directory
  create: all
  match: "**/*"
- type: document
  path: content/posts
  label: Modify Document
upload_dir: src/images/jpg
public_path: src/images/jpg
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: gatsby build
